#!/bin/sh

set -e
set -f

export MIMIR_DIR=$(dirname $0)
export MIMIR_DB_DIR=$MIMIR_DIR/db
. $MIMIR_DIR/mimir.conf
cmddir=$MIMIR_DIR/cmds

# Right on - read commands and be merry.

dateregex='[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}'
# TODO - replace this Awk stuff with sed and/or grep.
awk_checkpart='/'$dateregex' -!- .* has left '$irc_channel'$/ { print substr($4, 0, index($4, "(")-1)}'
awk_getcmd='/'$dateregex' <[A-Za-z0-9_]*> '$irc_username': / { print $5; }'
awk_getuser='{ print substr($3, 2, length($3)-2); }'
awk_getargs='{ print substr($0, index($0, " "$5)+length($5)+2, length($0)) }'

broke() {
    echo "Command returned a non-zero status."
}

export LC_ALL=da_DK.UTF-8

. $MIMIR_DIR/mimir.lib

echo "Using channel in $irc_dir/$irc_server/$irc_channel"

tail -f -n 0 "$irc_dir/$irc_server/$irc_channel/out" | while read line; do
    rawcmd=$(echo "$line"|awk --posix "$awk_getcmd")
    if [ "$rawcmd" ]; then
        cmd=$(basename -- "$rawcmd")
        export CMD_USER="$(echo "$line"|awk --posix "$awk_getuser"|sed 's/_*$//')"
        export CMD_ARGS="$(echo "$line"|awk --posix "$awk_getargs")"
        export CMD_LINE="$line"
        if [ "$cmd" ] && [ "$CMD_USER" != "$irc_username" ]; then
            if [ -x "$cmddir/$cmd" ] && [ -f "$cmddir/$cmd" ]; then
                $cmddir/$cmd $CMD_ARGS || broke
            else
                echo "$CMD_USER: command not found: $cmd."
            fi
        fi
    fi
    part="$(echo "$line"|awk --posix "$awk_checkpart"|sed 's/_*$//')"
    if [ "$part" ]; then
        parted "$part"
    fi
done > "$irc_dir/$irc_server/$irc_channel/in"
