#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Perform a search on Google.  Should Google prove insufficient, try
# my 'explain' command.

import urllib
import urllib2
import simplejson as json
import sys

query = " ".join(sys.argv[1:])

results = 1
url = (u'http://ajax.googleapis.com/ajax/services/search/web'
       u'?v=1.0&start=0&rsz=' + str(results) + u'&q=' + urllib.quote(query))

request = urllib2.Request(url, None)
response = urllib2.urlopen(request)

results = json.load(response)
#print json.dumps(results, sort_keys=True, indent=4)

if len(results["responseData"]["results"]) == 0:
    print "No results from Google."
else:
    first_result = results["responseData"]["results"][0];
    unicodestr = first_result["titleNoFormatting"] + " (" + first_result["url"] + ")"
    print unicodestr.encode('UTF-8')

